import { useState } from "react";

const blankTarget = { id: "", kind: "swarm", employees: [], swarmId: "", deviceId: "", threadId: "", projectId: "", url: "", secretRef: "", turnLimit: "1" };
const Field = ({ label, children }) => <label className="org-field"><span>{label}</span>{children}</label>;

export default function OrganizationExecutionSettings({ organization, busy, onAction, onSave }) {
  const [target, setTarget] = useState(blankTarget);
  const [resolutions, setResolutions] = useState({});
  const [hook, setHook] = useState({ routineId: "", secretRef: "" });
  const [credential, setCredential] = useState({ id: "", value: "" });
  const { config, runtime } = organization;
  const patch = values => setTarget(t => ({ ...t, ...values }));
  const targets = config.executionTargets || [];
  const routines = Object.values(runtime.routines || {});
  const unresolved = Object.values(runtime.attempts || {}).filter(a => a.executionHandle && !a.executionHandle.settled && a.status !== "running");
  async function backup() {
    const result = await onAction("backup");
    if (!result) return;
    const url = URL.createObjectURL(new Blob([Uint8Array.from(atob(result.content), c => c.charCodeAt(0))], { type: "application/vnd.sqlite3" }));
    const link = document.createElement("a"); link.href = url; link.download = result.filename; link.click();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  return <>
    <section className="org-operation-section"><h4>Execution destinations</h4><p className="org-note">Grant a destination to selected employees. Tasks reserve its turn limit before starting. Each managed run uses one concurrent slot.</p>
      {targets.map(t => <article key={t.id} className="org-routine"><div><strong>{t.id}</strong><p className="org-note">{t.kind} · {t.turnLimit} reserved turns · {t.employees.join(", ")}</p></div><div className="org-actions"><button className="org-button" disabled={busy} onClick={() => setTarget({ ...blankTarget, ...t, turnLimit: String(t.turnLimit) })}>Edit destination</button><button className="org-button" disabled={busy} onClick={() => onSave({ ...config, executionTargets: targets.filter(x => x.id !== t.id) }, `Revoked destination ${t.id}`, organization.revision)}>Revoke destination</button></div></article>)}
      <details><summary>Add or edit a destination</summary><form className="org-form" onSubmit={async e => { e.preventDefault(); const value = { id: target.id, kind: target.kind, employees: target.employees, turnLimit: target.kind === "fleet" ? 1 : Number(target.turnLimit), ...(target.kind === "swarm" ? { swarmId: target.swarmId } : target.kind === "fleet" ? { deviceId: target.deviceId, threadId: target.threadId, projectId: target.projectId } : { url: target.url, secretRef: target.secretRef }) }; if (await onSave({ ...config, executionTargets: [...targets.filter(t => t.id !== value.id), value] }, `Saved execution destination ${value.id}`, organization.revision)) setTarget(blankTarget); }}>
        <Field label="Destination ID"><input value={target.id} onChange={e => patch({ id: e.target.value })} required pattern={"[A-Za-z0-9][A-Za-z0-9_\\-]{0,99}"} /></Field>
        <Field label="Execution runtime"><select value={target.kind} onChange={e => patch({ kind: e.target.value })}><option value="swarm">Local swarm</option><option value="fleet">Paired desktop</option><option value="remote">HTTPS job gateway</option></select></Field>
        <fieldset><legend>Employees allowed to use this destination</legend>{config.employees.map(employee => <label className="org-check" key={employee.id}><input type="checkbox" checked={target.employees.includes(employee.id)} onChange={e => patch({ employees: e.target.checked ? [...target.employees, employee.id] : target.employees.filter(id => id !== employee.id) })} />{employee.name}</label>)}</fieldset>
        {(target.kind === "swarm" ? [["swarmId", "Swarm ID"]] : target.kind === "fleet" ? [["deviceId", "Paired desktop ID"], ["threadId", "Granted thread ID"], ["projectId", "Target project ID"]] : [["url", "HTTPS gateway base URL"], ["secretRef", "Granted secret reference ID"]]).map(([key, label]) => <Field key={key} label={label}><input required value={target[key] || ""} onChange={e => patch({ [key]: e.target.value })} /></Field>)}
        {target.kind !== "fleet" && <Field label="Reserved provider turns"><input inputMode="numeric" required value={target.turnLimit} onChange={e => patch({ turnLimit: e.target.value })} /></Field>}
        <p className="org-note">Saving destination grants pauses the organization and stops active work. Start it again after reviewing the change.</p><button className="org-button" disabled={busy || !target.employees.length}>Save destination</button>
      </form></details>
      {!!unresolved.length && <div className="org-banner org-pause"><p>{unresolved.length} execution receipts need stop confirmation. New work is held.</p><button className="org-button" disabled={busy} onClick={() => onAction("execution_reconcile")}>Check stopped executions</button>{unresolved.map(a => <form className="org-form" key={a.id} onSubmit={e => { e.preventDefault(); onAction("execution_resolve", { attemptId: a.id, reason: resolutions[a.id], confirmStopped: true }); }}><p>{a.executionHandle.kind}: {a.executionHandle.error || "Waiting for target confirmation"}</p><Field label="Stop inspection evidence"><input required value={resolutions[a.id] || ""} onChange={e => setResolutions(r => ({ ...r, [a.id]: e.target.value }))} /></Field><button className="org-button" disabled={busy}>Confirm stopped after inspection</button></form>)}</div>}
    </section>
    <section className="org-operation-section"><h4>External routine triggers</h4><p className="org-note">Incoming requests need a timestamp, delivery ID and HMAC signature. They queue the configured routine task task template. Incoming text cannot change permissions or assignments.</p>
      {Object.entries(runtime.webhooks || {}).map(([id, value]) => { const routine = routines.find(r => r.id === id); return <article className="org-routine" key={id}><div><strong>{routine?.name || id}</strong><p className="org-note">{value.enabled ? "Enabled" : "Disabled"}<br /><code>/api/organization-webhooks/{organization.id}/{id}</code></p></div><button className="org-button" disabled={busy || !routine} onClick={() => onAction("webhook_save", { routineId: id, expectedRevision: routine.revision, secretRef: value.secretRef, enabled: !value.enabled })}>{value.enabled ? "Disable webhook" : "Enable webhook"}</button></article>; })}
      <form className="org-inline-form" onSubmit={e => { e.preventDefault(); const routine = routines.find(r => r.id === hook.routineId); onAction("webhook_save", { ...hook, expectedRevision: routine.revision, enabled: true }); }}><Field label="Routine to trigger"><select required value={hook.routineId} onChange={e => setHook(h => ({ ...h, routineId: e.target.value }))}><option value="">Choose routine</option>{routines.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select></Field><Field label="Signing secret reference"><select required value={hook.secretRef} onChange={e => setHook(h => ({ ...h, secretRef: e.target.value }))}><option value="">Choose secret</option>{Object.values(runtime.secrets || {}).filter(s => !s.revoked).map(s => <option key={s.id} value={s.id}>{s.id}</option>)}</select></Field><button className="org-button" disabled={busy}>Enable signed webhook</button></form>
    </section>
    <section className="org-operation-section"><h4>Protected credentials and recovery</h4><details><summary>Store or rotate a credential</summary><form className="org-form" onSubmit={async e => { e.preventDefault(); if (await onAction("secret_store", credential)) setCredential({ id: "", value: "" }); }}><Field label="Credential reference ID"><input required value={credential.id} onChange={e => setCredential(c => ({ ...c, id: e.target.value }))} /></Field><Field label="Credential value"><input type="password" autoComplete="new-password" required value={credential.value} onChange={e => setCredential(c => ({ ...c, value: e.target.value }))} /></Field><p className="org-note">Saved in the operating system keyring. Rotation stops affected employees. The credential is omitted from organization exports and history.</p><button className="org-button" disabled={busy}>Store credential</button></form></details><p className="org-note">Download a consistent SQLite backup of all organizations, including work, history and run receipts. Credentials remain in the OS keyring. Restore the file with Raticode closed.</p><button className="org-button" disabled={busy} onClick={backup}>Download operational backup</button></section>
  </>;
}
