import { useState } from "react";
import OrganizationExecutionSettings from "./OrganizationExecutionSettings.jsx";
import { formatUsd, organizationRequest } from "../lib/organizations.js";

const Field = ({ label, children }) => <label className="org-field"><span>{label}</span>{children}</label>;
const Text = ({ label, value, onChange, ...props }) => <Field label={label}><input value={value} onChange={e => onChange(e.target.value)} {...props} /></Field>;

export default function OrganizationOperations({ organization, busy, onAction, onSave }) {
  const { config, runtime, diagnostics = {} } = organization;
  const [preview, setPreview] = useState(null);
  const [outcomes, setOutcomes] = useState(null);
  const [error, setError] = useState("");
  const [duration, setDuration] = useState("60");
  const [routine, setRoutine] = useState({ name: "", title: "", assignee: "", cron: "0 9 * * 1-5", timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, overlap: "skip", missed: "coalesce" });
  const [goal, setGoal] = useState({ title: "", owner: "", parentId: "" });
  const [memory, setMemory] = useState({ body: "", path: "", employeeId: "" });
  const [experiment, setExperiment] = useState({ employeeId: "", taskIds: "", reason: "" });
  const [secret, setSecret] = useState({ id: "", account: "" });
  const routines = Object.values(runtime.routines || {});
  async function inspect(action, params, setter) {
    setError("");
    try { setter(await organizationRequest("", action, organization.id, params)); }
    catch (failure) { setError(failure.message); }
  }
  const patch = values => setRoutine(r => ({ ...r, ...values }));
  return <section className="org-operations" aria-label="Organization operations">
    <div className="org-section-heading"><div><h3>Operating desk</h3><p className="org-note">{diagnostics.effectiveConcurrency} effective concurrent turns, {diagnostics.configuredConcurrency} configured. Shared workspaces take turns.</p></div><button className="org-button" disabled={busy} onClick={() => onAction("resume_all", { expectedRevision: organization.revision })}>Resume all employees</button></div>
    {(diagnostics.budgetWarnings || []).map((warning, i) => <p key={i} className="org-banner org-pause">{warning.scope}: {warning.reason}</p>)}
    {error && <p role="alert" className="org-banner org-error">{error}</p>}
    <section className="org-operation-section"><h4>Rehearse the queue</h4><p className="org-note">Preview current work without starting employees. Dependencies and approvals stay unresolved in this estimate.</p>
      <form className="org-inline-form" onSubmit={e => { e.preventDefault(); inspect("rehearse", { assumedDurationSeconds: Number(duration) }, setPreview); }}><Text label="Assumed seconds per turn" inputMode="decimal" value={duration} onChange={setDuration} required /><button className="org-button org-primary">Rehearse</button></form>
      {preview && <><p className="org-note">{preview.historicalSamples} completed runs available. Heartbeats could add up to {preview.heartbeatTurnsPerDay.toFixed(1)} turns per day while idle.</p><div className="org-table-scroll"><table className="org-operation-table"><thead><tr><th>Task</th><th>Not running because</th><th>Estimated start</th></tr></thead><tbody>{preview.tasks.map(task => <tr key={task.taskId}><td>{task.title}</td><td>{task.reason}</td><td>{task.startSeconds == null ? "Unscheduled" : `${task.startSeconds}s`}</td></tr>)}</tbody></table></div></>}
    </section>
    <section className="org-operation-section"><div className="org-section-heading"><h4>Goals and accepted outcomes</h4><button className="org-button" onClick={() => inspect("outcomes", {}, setOutcomes)}>Refresh outcomes</button></div>
      {(config.goalRecords || []).map(record => <p key={record.id}><strong>{record.title}</strong> · {record.status} · {config.employees.find(e => e.id === record.owner)?.name || "No owner"}</p>)}
      <details><summary>Add a goal</summary><form className="org-form" onSubmit={async e => { e.preventDefault(); const next = { id: crypto.randomUUID(), ...goal, owner: goal.owner || null, parentId: goal.parentId || null, status: "active" }; if (await onSave({ ...config, goalRecords: [...(config.goalRecords || []), next] }, `Added goal: ${goal.title}`, organization.revision)) setGoal({ title: "", owner: "", parentId: "" }); }}><Text label="Goal title" value={goal.title} onChange={title => setGoal(g => ({ ...g, title }))} required /><Field label="Goal owner"><select value={goal.owner} onChange={e => setGoal(g => ({ ...g, owner: e.target.value }))}><option value="">No owner</option>{config.employees.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></Field><Field label="Parent goal"><select value={goal.parentId} onChange={e => setGoal(g => ({ ...g, parentId: e.target.value }))}><option value="">Company goal</option>{(config.goalRecords || []).map(g => <option key={g.id} value={g.id}>{g.title}</option>)}</select></Field><button className="org-button" disabled={busy}>Save goal</button></form></details>
      {outcomes && <div className="org-table-scroll"><table className="org-operation-table"><thead><tr><th>Employee</th><th>Accepted</th><th>Rework</th><th>Known cost</th><th>Cost per accepted result</th></tr></thead><tbody>{outcomes.employees.map(row => <tr key={row.employeeId}><td>{config.employees.find(e => e.id === row.employeeId)?.name}</td><td>{row.reviewedAccepted}</td><td>{row.rework}</td><td>{formatUsd(row.knownCostUsd)}{row.unknownCostAttempts > 0 && ` + ${row.unknownCostAttempts} unknown`}</td><td>{formatUsd(row.costPerAcceptedOutcome)}</td></tr>)}</tbody></table><p className="org-note">{outcomes.routingAdvice}</p></div>}
      {outcomes?.suggestions?.map((item, index) => <p key={index}>Suggested cohort: {config.employees.find(e => e.id === item.candidate)?.name}. {item.reason}</p>)}
      {outcomes?.experiments?.map(item => <p key={item.id}>{item.reason}: {item.accepted}/{item.taskIds.length} accepted, {item.rework} revision requests.</p>)}
      <details><summary>Try a small routing cohort</summary><form className="org-form" onSubmit={e => { e.preventDefault(); onAction("routing_experiment", { ...experiment, taskIds: experiment.taskIds.split(",").map(id => id.trim()).filter(Boolean) }); }}><Field label="Cohort employee"><select required value={experiment.employeeId} onChange={e => setExperiment(x => ({ ...x, employeeId: e.target.value }))}><option value="">Choose employee</option>{config.employees.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></Field><Text label="Pending task IDs, comma separated, maximum 10" value={experiment.taskIds} onChange={taskIds => setExperiment(x => ({ ...x, taskIds }))} required /><Text label="Routing hypothesis" value={experiment.reason} onChange={reason => setExperiment(x => ({ ...x, reason }))} required /><p className="org-note">This reassigns the selected tasks, clears their plan approvals and requires completion review.</p><button className="org-button" disabled={busy}>Assign review cohort</button></form></details>
    </section>
    <section className="org-operation-section"><h4>Routines</h4><p className="org-note">Each occurrence creates a separate task. Schedules run while the organization is started.</p>
      {routines.map(item => <article className="org-routine" key={item.id}><div><strong>{item.name}</strong><p className="org-note">{item.cron || `${item.intervalSeconds}s interval`} · {item.timezone}<br />Next: {item.nextAt ? new Date(item.nextAt).toLocaleString() : "API trigger only"}<br />Previous task: {runtime.tasks.find(t => t.id === item.lastTaskId)?.status || "None"}</p></div><div className="org-actions"><button className="org-button" disabled={busy || !item.enabled} onClick={() => onAction("routine_trigger", { routineId: item.id, idempotencyKey: crypto.randomUUID() })}>Queue occurrence</button><button className="org-button" disabled={busy} onClick={() => onAction("routine_save", { routine: { ...item, enabled: !item.enabled }, expectedRevision: item.revision })}>{item.enabled ? "Disable" : "Enable"}</button></div></article>)}
      <details><summary>Add a routine</summary><form className="org-form" onSubmit={async e => { e.preventDefault(); if (await onAction("routine_save", { routine: { name: routine.name, cron: routine.cron || null, timezone: routine.timezone, overlap: routine.overlap, missed: routine.missed, task: { title: routine.title, assignee: routine.assignee || null } } })) patch({ name: "", title: "" }); }}><Text label="Routine name" value={routine.name} onChange={name => patch({ name })} required /><Text label="Task title" value={routine.title} onChange={title => patch({ title })} required /><Field label="Assigned employee"><select value={routine.assignee} onChange={e => patch({ assignee: e.target.value })}><option value="">Unassigned</option>{config.employees.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></Field><div className="org-form-grid"><Text label="Cron schedule, blank for API only" value={routine.cron} onChange={cron => patch({ cron })} /><Text label="Timezone" value={routine.timezone} onChange={timezone => patch({ timezone })} required /><Field label="When previous work is open"><select value={routine.overlap} onChange={e => patch({ overlap: e.target.value })}><option value="skip">Skip this occurrence</option><option value="queue">Queue after previous work</option></select></Field><Field label="When a run was missed"><select value={routine.missed} onChange={e => patch({ missed: e.target.value })}><option value="coalesce">Queue one catch-up occurrence</option><option value="skip">Skip missed occurrences</option></select></Field></div><button className="org-button" disabled={busy}>Save routine</button></form></details>
    </section>
    <section className="org-operation-section"><div className="org-section-heading"><h4>Memory evidence</h4><button className="org-button" disabled={busy} onClick={() => onAction("memory_check")}>Check source changes</button></div>
      {Object.values(runtime.memories || {}).map(item => <article key={item.id} className="org-memory"><strong>{item.stale ? "Stale: recheck queued" : "Verified"}</strong><p>{item.body}</p><small>{item.source.path}</small></article>)}
      <details><summary>Save a source-linked fact</summary><form className="org-form" onSubmit={async e => { e.preventDefault(); if (await onAction("memory_save", memory)) setMemory(m => ({ ...m, body: "" })); }}><Field label="Employee"><select required value={memory.employeeId} onChange={e => setMemory(m => ({ ...m, employeeId: e.target.value }))}><option value="">Choose employee</option>{config.employees.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></Field><Text label="Fact to retain" value={memory.body} onChange={body => setMemory(m => ({ ...m, body }))} required /><Text label="Source file, absolute path" value={memory.path} onChange={path => setMemory(m => ({ ...m, path }))} required /><button className="org-button" disabled={busy}>Save fact</button></form></details>
    </section>
    <section className="org-operation-section"><h4>Secret references</h4><p className="org-note">Reference credentials already held in the OS keyring service “Raticode organization secrets”. Use secret://reference-id in selected MCP environment values. Grant reference IDs in employee settings.</p>{Object.values(runtime.secrets || {}).map(item => <p key={item.id}>{item.id} · version {item.version} · {item.revoked ? "Revoked" : "Available"} <button className="org-button" disabled={busy || item.revoked} onClick={() => onAction("secret_reference", { ...item, revoked: true })}>Revoke</button></p>)}<details><summary>Add or rotate a reference</summary><form className="org-form" onSubmit={e => { e.preventDefault(); onAction("secret_reference", secret); }}><Text label="Reference ID" value={secret.id} onChange={id => setSecret(s => ({ ...s, id }))} required /><Text label="OS keyring account" value={secret.account} onChange={account => setSecret(s => ({ ...s, account }))} required /><button className="org-button" disabled={busy}>Save reference</button></form></details></section>
    <OrganizationExecutionSettings organization={organization} busy={busy} onAction={onAction} onSave={onSave} />
    <p className="org-note">{diagnostics.delegation} {diagnostics.isolation}</p>
  </section>;
}

export function TaskRunControls({ organization, task, busy, onAction }) {
  const [reason, setReason] = useState("");
  const [artifact, setArtifact] = useState({ path: "", attemptId: "", kind: "file" });
  const [preview, setPreview] = useState(null);
  const [error, setError] = useState("");
  const attempts = Object.values(organization.runtime.attempts || {}).filter(a => a.taskId === task.id);
  return <section className="org-operation-section" aria-label="Task controls"><p>{organization.diagnostics?.taskReasons?.[task.id]}</p><div className="org-actions">
    {task.claim && <button className="org-button" disabled={busy} onClick={() => onAction("task_update", { taskId: task.id, expectedRevision: task.revision, changes: { status: "cancelled" } })}>Cancel running task</button>}
    {["blocked", "cancelled", "done"].includes(task.status) && !task.claim && <button className="org-button" disabled={busy} onClick={() => onAction("reopen", { taskId: task.id, expectedRevision: task.revision })}>Reopen task</button>}
    {task.approvalRequired && task.approvedRevision == null && !["done", "cancelled"].includes(task.status) && <button className="org-button" disabled={busy} onClick={() => onAction("approve", { taskId: task.id, expectedRevision: task.revision })}>Approve plan</button>}
  </div>
    {task.status === "in_review" && !task.claim && <form onSubmit={e => e.preventDefault()} className="org-form"><Text label="Review reason" value={reason} onChange={setReason} required /><div className="org-actions">{[["accept", "Accept result"], ["revise", "Request revision"], ["reject", "Reject result"]].map(([decision, label]) => <button key={decision} className="org-button" disabled={busy || !reason.trim()} onClick={() => onAction("review", { taskId: task.id, expectedRevision: task.revision, decision, body: reason })}>{label}</button>)}</div></form>}
    {!!attempts.length && <details><summary>Run records and artifacts</summary>{attempts.map(a => <p key={a.id}><strong>{a.status}</strong> · {new Date(a.startedAt).toLocaleString()} · {a.elapsedSeconds?.toFixed(1) || "…"}s · {formatUsd(a.costUsd)}<br /><small>{a.workspacePath}{a.error && ` · ${a.error}`}</small></p>)}{task.artifacts?.map(a => <p key={a.id}>{a.kind}: {a.path}<br /><small>SHA-256 {a.sha256}</small></p>)}<form className="org-form" onSubmit={e => { e.preventDefault(); onAction("artifact_add", { taskId: task.id, ...artifact }); }}><Text label="Artifact file, absolute path" value={artifact.path} onChange={path => setArtifact(a => ({ ...a, path }))} required /><Field label="Result belongs to run"><select required value={artifact.attemptId} onChange={e => setArtifact(a => ({ ...a, attemptId: e.target.value }))}><option value="">Choose run</option>{attempts.map(a => <option key={a.id} value={a.id}>{new Date(a.startedAt).toLocaleString()} · {a.status}</option>)}</select></Field><Field label="Artifact kind"><select value={artifact.kind} onChange={e => setArtifact(a => ({ ...a, kind: e.target.value }))}>{["file", "diff", "test", "document"].map(kind => <option key={kind}>{kind}</option>)}</select></Field><button className="org-button" disabled={busy}>Attach evidence</button></form></details>}
    {task.workflowContract && <><button className="org-button" onClick={async () => { try { setPreview(await organizationRequest("", "workflow_preview", organization.id, { taskId: task.id })); setError(""); } catch (failure) { setError(failure.message); } }}>Validate workflow contract</button>{preview && <p role="status">Workflow compiled. {preview.preflightReady ? "Preflight passed." : "Preflight found missing resources."}<br /><small>IR SHA-256 {preview.irSha256}</small>{preview.preflightDiagnostics?.map((message, i) => <span key={i}>{message}</span>)}</p>}{preview && <><p className="org-note">Required grants: {preview.requiredResources?.join(", ")}</p><button className="org-button org-primary" disabled={busy || !!task.claim || !preview.preflightReady} onClick={() => onAction("workflow_launch", { taskId: task.id, expectedRevision: task.revision, irSha256: preview.irSha256 })}>Authorize workflow execution</button><p className="org-note">Queues this compiled workflow for execution when the organization is running. Changes to its source or contract require new authorization.</p></>}{error && <p role="alert">{error}</p>}</>}
  </section>;
}
